#!/bin/bash

function usage {
    echo "usage: $0 --keystore=<keystore_file> --password=<password> -r jar <file.apk>"
    echo -e "Required Parameters:"
    echo -e "\t   --keystore: the keystore file generated by keytool"
    echo -e "\t   --password: the password for the keystore, which is the same with that for private key"
    echo -e "\t   -r jar: the apk file to sign"
    echo -e "Optional Parameters:"
    echo -e "\t   --help | -h: display this usage message"
}

#Parse arguments
for i in $@; do
    case $i in
    --keystore=*)
        KEYSTORE=${i#*=}
        if [ ! -f $KEYSTORE ]; then
            echo "ERROR: $KEYSTORE not a valid file." >&2
            exit 1
        fi
        ;;
    --password=*)
        PASSWORD=${i#*=}
        ;;
    --help|-h)
        usage
        exit 0
        ;;
    *)
    esac
done

#Make sure there are enough paramters
if [ $# -lt 5 ]; then
    usage
    exit 1
fi 

#Verify required paramters
if [ ! $KEYSTORE ]; then
    echo "--keystore is required" >&2
    usage
    exit 1
elif [ ! $PASSWORD ]; then
    echo "--password is required" >&2
    usage
    exit 1
fi

apkfile=$5
zip -dq $apkfile META-INF\*
jarsigner -keystore $KEYSTORE -storepass $PASSWORD -keypass $PASSWORD $apkfile RELEASE
